apiVersion: v1
kind: Service
metadata:  
  labels:
    run: statsd
  name: statsd  
spec:
  ports:
  - port: 8125
    name: statsd-udp
    protocol: UDP
    targetPort: 8125
  - port: 8126
    name: statsd-tcp
    protocol: TCP
    targetPort: 8126
  selector:
    run: statsd
  sessionAffinity: None
  type: ClusterIP
