apiVersion: "config.istio.io/v1alpha2"
kind: metric
metadata:
  name: apigatewayrequestcount
  namespace: istio-system
spec:
  value: "1"
  dimensions:
    source: source.workload.name | "unknown"
    destination: destination.workload.name | "unknown"
    destination_ip: destination.ip
  monitored_resource_type: '"UNSPECIFIED"'
---
apiVersion: "config.istio.io/v1alpha2"
kind: prometheus
metadata:
  name: apigatewayrequestcounthandler
  namespace: istio-system
spec:
  metrics:
    - name: apigateway_request_count
      instance_name: apigatewayrequestcount.metric.istio-system
      kind: COUNTER
      label_names:
        - source
        - destination
        - destination_ip
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: apigatewayrequestcountrule
  namespace: istio-system
spec:
  match: destination.service == "apigateway.istioinaction.svc.cluster.local"
  actions:
    - handler: apigatewayrequestcounthandler.prometheus
      instances:
        - apigatewayrequestcount.metric